### ISSUE TITLE
Unhelpful comments (form NMDC DataHarmonizer perspective)

### ISSUE THREAD

**Issue by turbomam** [cmungall/mixs-source#12]
"This field is used uniquely in: {packages_str}"
"This field is used in: {len(s.keys())} packages: {packages_str}"

**Comment by turbomam** [comment]
New example, with no usage comments:

```yaml
  air_carb_dioxide:
    name: air_carb_dioxide
    definition_uri: https://w3id.org/mixs/vocab/carb_dioxide
    mappings:
    - MIXS:0000097
    description: Carbon dioxide (gas) amount or concentration at the time of sampling
    title: carbon dioxide
    comments:
    - 'Expected value: measurement value'
    - 'Preferred unit: micromole per liter, parts per million'
    - 'Occurrence: 1'
    examples:
    - value: 410 parts per million
    from_schema: http://w3id.org/mixs/terms
    is_a: carb_dioxide
    domain: air
    slot_uri: MIXS:0000097
    multivalued: false
    inlined: true
    alias: carb_dioxide
    owner: air
    domain_of:
    - air
    is_usage_slot: true
    usage_slot_name: carb_dioxide
    range: quantity value
    required: false
```
